export const airports: any = [
  {
    iataCode: 'CHB',
    airportName: 'Chilas Airport',
    location: 'Chilas',
    country: 'Pakistan',
  },
  {
    iataCode: 'MFG',
    airportName: 'Muzaffarabad Airport',
    location: 'Muzaffarabad',
    country: 'Pakistan',
  },
  {
    iataCode: 'KDD',
    airportName: 'Khuzdar Airport',
    location: 'Khuzdar',
    country: 'Pakistan',
  },
  {
    iataCode: 'SWN',
    airportName: 'Sahiwal Airport',
    location: 'Sahiwal',
    country: 'Pakistan',
  },
  {
    iataCode: 'AAW',
    airportName: 'Abbottabad Airport',
    location: 'Abbottabad',
    country: 'Pakistan',
  },
  {
    iataCode: 'KDU',
    airportName: 'Skardu Airport',
    location: 'Skardu',
    country: 'Pakistan',
  },
  {
    iataCode: 'CJL',
    airportName: 'Chitral Airport',
    location: 'Chitral',
    country: 'Pakistan',
  },
  {
    iataCode: 'CWP',
    airportName: 'Campbellpore Airport',
    location: 'Campbellpore',
    country: 'Pakistan',
  },
  {
    iataCode: 'SKT',
    airportName: 'Sialkot International Airport',
    location: 'Sialkot',
    country: 'Pakistan',
  },
  {
    iataCode: 'LHE',
    airportName: 'Allama Iqbal International Airport',
    location: 'Lahore',
    country: 'Pakistan',
  },
  {
    iataCode: 'JIW',
    airportName: 'Jiwani Airport',
    location: 'Jiwani',
    country: 'Pakistan',
  },
  {
    iataCode: 'BNP',
    airportName: 'Bannu Airport',
    location: 'Bannu, North-West Frontier Province',
    country: 'Pakistan',
  },
  {
    iataCode: 'SKZ',
    airportName: 'Sukkur Airport',
    location: 'Sukkur',
    country: 'Pakistan',
  },
  {
    iataCode: 'GRT',
    airportName: 'Gujrat Airport',
    location: 'Gujrat',
    country: 'Pakistan',
  },
  {
    iataCode: 'DSK',
    airportName: 'Dera Ismail Khan Airport',
    location: 'Dera Ismail Khan',
    country: 'Pakistan',
  },
  {
    iataCode: 'BDN',
    airportName: 'Talhar Airport',
    location: 'Badin',
    country: 'Pakistan',
  },
  {
    iataCode: 'KHI',
    airportName: "Jinnah International Airport (Quaid-e-Azam Int'l)",
    location: 'Karachi',
    country: 'Pakistan',
  },
  {
    iataCode: 'MJD',
    airportName: 'Moenjodaro Airport',
    location: 'Moenjodaro',
    country: 'Pakistan',
  },
  {
    iataCode: 'WGB',
    airportName: 'Bahawalnagar Airport',
    location: 'Bahawalnagar',
    country: 'Pakistan',
  },
  {
    iataCode: 'UET',
    airportName: 'Quetta International Airport',
    location: 'Quetta',
    country: 'Pakistan',
  },
  {
    iataCode: 'MUX',
    airportName: 'Multan International Airport',
    location: 'Multan',
    country: 'Pakistan',
  },
  {
    iataCode: 'LYP',
    airportName: 'Faisalabad International Airport',
    location: 'Faisalabad',
    country: 'Pakistan',
  },
  {
    iataCode: 'HRA',
    airportName: 'Mansehra Airport',
    location: 'Mansehra',
    country: 'Pakistan',
  },
  {
    iataCode: 'ATG',
    airportName: 'Attock Airport',
    location: 'Attock',
    country: 'Pakistan',
  },
  {
    iataCode: 'DBA',
    airportName: 'Dalbandin Airport',
    location: 'Dalbandin',
    country: 'Pakistan',
  },
  {
    iataCode: 'MWD',
    airportName: 'PAF Base Mianwali',
    location: 'Mianwali',
    country: 'Pakistan',
  },
  {
    iataCode: 'PEW',
    airportName: 'Peshawar Airport',
    location: 'Peshawar',
    country: 'Pakistan',
  },
  {
    iataCode: 'PZH',
    airportName: 'Zhob Airport',
    location: 'Zhob',
    country: 'Pakistan',
  },
  {
    iataCode: 'GWD',
    airportName: 'Gwadar Airport',
    location: 'Gwadar',
    country: 'Pakistan',
  },
  {
    iataCode: 'ISB',
    airportName:
      'Benazir Bhutto International Airport (Islamabad International)',
    location: 'Islamabad / Rawalpindi',
    country: 'Pakistan',
  },
  {
    iataCode: 'DDU',
    airportName: 'Dadu Airport',
    location: 'Dadu',
    country: 'Pakistan',
  },
  {
    iataCode: 'DEA',
    airportName: 'Dera Ghazi Khan Airport',
    location: 'Dera Ghazi Khan',
    country: 'Pakistan',
  },
  {
    iataCode: 'BHC',
    airportName: 'Bhurban Heliport',
    location: 'Bhurban',
    country: 'Pakistan',
  },
  {
    iataCode: 'BHV',
    airportName: 'Bahawalpur Airport',
    location: 'Bahawalpur',
    country: 'Pakistan',
  },
  {
    iataCode: 'BHW',
    airportName: 'Bhagatanwala Airport',
    location: 'Sargodha',
    country: 'Pakistan',
  },
  {
    iataCode: 'PJG',
    airportName: 'Panjgur Airport',
    location: 'Panjgur',
    country: 'Pakistan',
  },
  {
    iataCode: 'OHT',
    airportName: 'Kohat Airport',
    location: 'Kohat',
    country: 'Pakistan',
  },
  {
    iataCode: 'GIL',
    airportName: 'Gilgit Airport',
    location: 'Gilgit',
    country: 'Pakistan',
  },
  {
    iataCode: 'KBH',
    airportName: 'Kalat Airport',
    location: 'Kalat',
    country: 'Pakistan',
  },
  {
    iataCode: 'HDD',
    airportName: 'Hyderabad Airport',
    location: 'Hyderabad',
    country: 'Pakistan',
  },
  {
    iataCode: 'MPD',
    airportName: 'Sindhri Tharparkar Airport (Mirpur Khas Airport)',
    location: 'Sindhri Tharparkar',
    country: 'Pakistan',
  },
  {
    iataCode: 'LRG',
    airportName: 'Loralai Airport',
    location: 'Loralai',
    country: 'Pakistan',
  },
  {
    iataCode: 'JAG',
    airportName: 'Jacobabad Air Base (Shahbaz Air Base)',
    location: 'Jacobabad',
    country: 'Pakistan',
  },
  {
    iataCode: 'KCF',
    airportName: 'Kadanwari Airport',
    location: 'Kadanwari',
    country: 'Pakistan',
  },
  {
    iataCode: 'TQN',
    airportName: 'Taloqan Airport',
    location: 'Taloqan',
    country: 'Afghanistan',
  },
  {
    iataCode: 'SGA',
    airportName: 'Sheghnan Airport',
    location: 'Sheghnan',
    country: 'Afghanistan',
  },
  {
    iataCode: 'ZAJ',
    airportName: 'Zaranj Airport',
    location: 'Zaranj',
    country: 'Afghanistan',
  },
  {
    iataCode: 'KDH',
    airportName: 'Kandahar International Airport',
    location: 'Kandahar',
    country: 'Afghanistan',
  },
  {
    iataCode: 'GRG',
    airportName: 'Gardez Airport',
    location: 'Gardez',
    country: 'Afghanistan',
  },
  {
    iataCode: 'IMZ',
    airportName: 'Nimroz Airport',
    location: 'Nimroz',
    country: 'Afghanistan',
  },
  {
    iataCode: 'KHT',
    airportName: 'Khost Airport',
    location: 'Khost',
    country: 'Afghanistan',
  },
  {
    iataCode: 'KUR',
    airportName: 'Razer Airport',
    location: 'Kron Monjan (Karanomunjan)',
    country: 'Afghanistan',
  },
  {
    iataCode: 'KWH',
    airportName: 'Khwahan Airport',
    location: 'Khwahan',
    country: 'Afghanistan',
  },
  {
    iataCode: 'DAZ',
    airportName: 'Darwaz Airport',
    location: 'Darwaz, Badakhshan',
    country: 'Afghanistan',
  },
  {
    iataCode: 'FAH',
    airportName: 'Farah Airport',
    location: 'Farah',
    country: 'Afghanistan',
  },
  {
    iataCode: 'GLM',
    airportName: 'Glenormiston Airport',
    location: 'Glenormiston, Queensland',
    country: 'Australia',
  },
  {
    iataCode: 'AAB',
    airportName: 'Arrabury Airport',
    location: 'Arrabury, Queensland',
    country: 'Australia',
  },
  {
    iataCode: 'BVI',
    airportName: 'Birdsville Airport',
    location: 'Birdsville, Queensland',
    country: 'Australia',
  },
  {
    iataCode: 'MET',
    airportName: 'Moreton Airport',
    location: 'Moreton, Queensland',
    country: 'Australia',
  },
  {
    iataCode: 'RDA',
    airportName: 'Rockhampton Downs Airport',
    location: 'Rockhampton Downs, Northern Territory',
    country: 'Australia',
  },
  {
    iataCode: 'DLV',
    airportName: 'Delissaville Airport',
    location: 'Delissaville, Northern Territory',
    country: 'Australia',
  },
  {
    iataCode: 'GLT',
    airportName: 'Gladstone Airport',
    location: 'Gladstone, Queensland',
    country: 'Australia',
  },
  {
    iataCode: 'LDC',
    airportName: 'Lindeman Island Airport',
    location: 'Lindeman Island, Queensland',
    country: 'Australia',
  },
  {
    iataCode: 'FOP',
    airportName: 'Morris Army Airfield',
    location: 'Fort Gillem, Forest Park, Georgia',
    country: 'USA',
  },
  {
    iataCode: 'VIA',
    airportName: 'Videira Airport',
    location: 'Videira, Santa Catarina',
    country: 'Brazil',
  },
  {
    iataCode: 'BVH',
    airportName: 'Vilhena Airport',
    location: 'Vilhena, Rondônia',
    country: 'Brazil',
  },
  {
    iataCode: 'LDB',
    airportName: 'Londrina Airport',
    location: 'Londrina, Paraná',
    country: 'Brazil',
  },
  {
    iataCode: 'MEU',
    airportName: 'Monte Dourado Airport',
    location: 'Almeirim, Pará',
    country: 'Brazil',
  },
  {
    iataCode: 'AAG',
    airportName: 'Arapoti Airport',
    location: 'Arapoti, Paraná',
    country: 'Brazil',
  },
  {
    iataCode: 'BVM',
    airportName: 'Belmonte Airport',
    location: 'Belmonte, Bahia',
    country: 'Brazil',
  },
  {
    iataCode: 'AAI',
    airportName: 'Arraias Airport',
    location: 'Arraias, Tocantins',
    country: 'Brazil',
  },
  {
    iataCode: 'BVS',
    airportName: 'Breves Airport',
    location: 'Breves, Pará',
    country: 'Brazil',
  },
  {
    iataCode: 'REC',
    airportName: 'Guararapes International Airport',
    location: 'Recife',
    country: 'Brazil',
  },
  {
    iataCode: 'MQH',
    airportName: 'Minaçu Airport',
    location: 'Minaçu, Goiás',
    country: 'Brazil',
  },
  {
    iataCode: 'CTP',
    airportName: 'Carutapera Airport',
    location: 'Carutapera, Maranhão',
    country: 'Brazil',
  },
  {
    iataCode: 'CSY',
    airportName: 'Cheboksary Airport',
    location: 'Cheboksary, Chuvashia',
    country: 'Russia',
  },
  {
    iataCode: 'IAR',
    airportName: 'Yaroslavl Airport',
    location: 'Yaroslavl',
    country: 'Russia',
  },
  {
    iataCode: 'VHV',
    airportName: 'Verkhnevilyuysk Airport',
    location: 'Verkhnevilyuysk, Woehee Bueluue District, Sakha Republic',
    country: 'Russia',
  },
  {
    iataCode: 'ONK',
    airportName: 'Olenyok Airport',
    location: 'Olenyok, Sakha Republic',
    country: 'Russia',
  },
  {
    iataCode: 'KCK',
    airportName: 'Kirensk Airport',
    location: 'Kirensk, Irkutsk Oblast',
    country: 'Russia',
  },
  {
    iataCode: 'LDG',
    airportName: 'Leshukonskoye Airport',
    location: 'Leshukonskoye',
    country: 'Russia',
  },
  {
    iataCode: 'AMV',
    airportName: 'Amderma Airport',
    location: 'Amderma',
    country: 'Russia',
  },
  {
    iataCode: 'SVO',
    airportName: 'Sheremetyevo International Airport',
    location: 'Moscow',
    country: 'Russia',
  },
  {
    iataCode: 'DME',
    airportName: 'Domodedovo International Airport',
    location: 'Moscow',
    country: 'Russia',
  },
  {
    iataCode: 'SGC',
    airportName: 'Surgut Airport',
    location: 'Surgut',
    country: 'Russia',
  },
  {
    iataCode: 'MQF',
    airportName: 'Magnitogorsk Airport',
    location: 'Magnitogorsk, Chelyabinsk',
    country: 'Russia',
  },
  {
    iataCode: 'SVX',
    airportName: 'Koltsovo International Airport',
    location: 'Yekaterinburg',
    country: 'Russia',
  },
  {
    iataCode: 'YLJ',
    airportName: 'Meadow Lake Airport',
    location: 'Meadow Lake, Saskatchewan',
    country: 'Canada',
  },
  {
    iataCode: 'YZT',
    airportName: 'Port Hardy Airport',
    location: 'Port Hardy, British Columbia',
    country: 'Canada',
  },
  {
    iataCode: 'XKO',
    airportName: 'Kemano Airport',
    location: 'Kemano, British Columbia',
    country: 'Canada',
  },
  {
    iataCode: 'YLL',
    airportName: 'Lloydminster Airport',
    location: 'Lloydminster, Alberta/Saskatchewan',
    country: 'Canada',
  },
  {
    iataCode: 'YZU',
    airportName: 'Whitecourt Airport',
    location: 'Whitecourt, Alberta',
    country: 'Canada',
  },
  {
    iataCode: 'XKS',
    airportName: 'Kasabonika Airport',
    location: 'Kasabonika First Nation, Ontario',
    country: 'Canada',
  },
  {
    iataCode: 'YZV',
    airportName: 'Sept-Îles Airport',
    location: 'Sept-Îles, Quebec',
    country: 'Canada',
  },
  {
    iataCode: 'LRQ',
    airportName: 'Laurie River Airport',
    location: 'Laurie River, Manitoba',
    country: 'Canada',
  },
  {
    iataCode: 'YLO',
    airportName: 'Shilo Airport',
    location: 'Shilo, Manitoba',
    country: 'Canada',
  },
  {
    iataCode: 'YZW',
    airportName: 'Teslin Airport',
    location: 'Teslin, Yukon',
    country: 'Canada',
  },
  {
    iataCode: 'XLB',
    airportName: 'Lac Brochet Airport',
    location: 'Lac Brochet, Manitoba',
    country: 'Canada',
  },
  {
    iataCode: 'YLP',
    airportName: 'Mingan Airport',
    location: 'Mingan, Quebec',
    country: 'Canada',
  },
  {
    iataCode: 'YZX',
    airportName: 'CFB Greenwood / Greenwood Airport',
    location: 'Greenwood, Nova Scotia',
    country: 'Canada',
  },
];
