export const stations: any = [
  { value: '892', name: 'ABDUL HAKIM' },
  { value: '555', name: 'ABDULLAHABAD (HALT)' },
  { value: '765', name: 'AB-I-GUM' },
  { value: '1041', name: 'AJNALA' },
  { value: '1242', name: 'AKHTAR KARNANA' },
  { value: '403', name: 'AKORA KHATTAK' },
  { value: '694', name: 'ALA' },
  { value: '972', name: 'ALIPUR CHATTHA' },
  { value: '621', name: 'ALLUWALI' },
  { value: '493', name: 'ARIF WALA' },
  { value: '585', name: 'ASHANPUR AHP' },
  { value: '398', name: 'ATTOCK CITY JN.' },
  { value: '446', name: 'BADAH' },
  { value: '306', name: 'BADAMI BAGH' },
  { value: '1130', name: 'BADDOMALHI' },
  { value: '473', name: 'BADIN' },
  { value: '1115', name: 'BAHALIKE' },
  { value: '167', name: 'BAHAWALPUR' },
  { value: '1186', name: 'BAKHTIARABAD DOMKI' },
  { value: '902', name: 'BALDHER' },
  { value: '556', name: 'BALOCHABAD' },
  { value: '1225', name: 'BANDHI' },
  { value: '1050', name: 'BANH MIANWALA (HALT)' },
  { value: '877', name: 'BASAL JN.' },
  { value: '1207', name: 'BASAL SHARIF' },
  { value: '503', name: 'BASIPPUR' },
  { value: '609', name: 'BEHAL' },
  { value: '796', name: 'BELELI' },
  { value: '612', name: 'BHAKKAR' },
  { value: '1043', name: 'BHALWAL' },
  { value: '91', name: 'BHIRIA ROAD' },
  { value: '21', name: 'BIN QASIM' },
  { value: '228', name: 'BOSTAN JN.' },
  { value: '31', name: 'BRAUDABAD' },
  { value: '1081', name: 'BUCHIANA' },
  { value: '575', name: 'BUDH' },
  { value: '1054', name: 'BURJ' },
  { value: '1052', name: 'CHAK JHUMRA JN.' },
  { value: '383', name: 'CHAK LALA' },
  { value: '732', name: 'CHAK SAIDA' },
  { value: '1241', name: 'CHAK SHER MUHAMMAD' },
  { value: '1091', name: 'CHAK TURAN' },
  { value: '48', name: 'CHAMAN' },
  { value: '1208', name: 'CHANAB NAGAR' },
  { value: '1009', name: 'CHARNALI' },
  { value: '819', name: 'CHAWINDA' },
  { value: '771', name: 'CHHAB' },
  { value: '524', name: 'CHHOR' },
  { value: '250', name: 'CHICHAWATNI ROAD' },
  { value: '1110', name: 'CHICHOKI MALLIAN' },
  { value: '698', name: 'CHILIANWALA' },
  { value: '1056', name: 'CHINIOT' },
  { value: '996', name: 'CHUND' },
  { value: '776', name: 'CHUR SHARIF (HALT)' },
  { value: '26', name: 'DABHEJI' },
  { value: '1209', name: 'DADU' },
  { value: '133', name: 'DAHARKI' },
  { value: '947', name: 'DAR UL IHSAN' },
  { value: '894', name: 'DARKHANA' },
  { value: '1206', name: 'DARYA KHAN' },
  { value: '1216', name: 'DAUD KHEL' },
  { value: '86', name: 'DAUR' },
  { value: '1184', name: 'DERA ALLAHYAR' },
  { value: '584', name: 'DERA DINPANAH' },
  { value: '1019', name: 'DERA GHAZI KHAN' },
  { value: '1185', name: 'DERA MURAD JAMALI' },
  { value: '162', name: 'DERA NAWAB SAHIB' },
  { value: '331', name: 'DHAUNKAL' },
  { value: '528', name: 'DHORO NARO' },
  { value: '364', name: 'DINA' },
  { value: '700', name: 'DINGA' },
  { value: '778', name: 'DOMEL' },
  { value: '1017', name: 'DOST MUHAMMAD ABAD' },
  { value: '12', name: 'DRIGH ROAD' },
  { value: '189', name: 'DUNYAPUR' },
  { value: '325', name: 'EMINABAD' },
  { value: '1183', name: 'FAISALABAD' },
  { value: '1113', name: 'FAROOQ ABAD' },
  { value: '882', name: 'FATEHJANG' },
  { value: '156', name: 'FIROZA' },
  { value: '490', name: 'GAGOO' },
  { value: '106', name: 'GAMBAT' },
  { value: '330', name: 'GHAKKHAR MANDI' },
  { value: '130', name: 'GHOTKI' },
  { value: '534', name: 'GILAWALA' },
  { value: '930', name: 'GOJRA' },
  { value: '1194', name: 'GOLRA SHARIF' },
  { value: '373', name: 'GUJAR KHAN' },
  { value: '719', name: 'GUJJAR' },
  { value: '328', name: 'GUJRANWALA' },
  { value: '327', name: 'GUJRANWALA CITY' },
  { value: '350', name: 'GUJRAT' },
  { value: '40', name: 'GULISTAN' },
  { value: '817', name: 'GUNNA KALAN' },
  { value: '580', name: 'GURMANI' },
  { value: '969', name: 'HAFIZABAD' },
  { value: '83', name: 'HAIBAT SHAHID' },
  { value: '693', name: 'HARIAH' },
  { value: '900', name: 'HARIPUR HAZARA' },
  { value: '393', name: 'HASAN ABDAL' },
  { value: '526', name: 'HASISAR' },
  { value: '501', name: 'HAVELI WASAWEWALA' },
  { value: '904', name: 'HAVELIAN' },
  { value: '50', name: 'HYDERABAD JN' },
  { value: '769', name: 'INJRA' },
  { value: '726', name: 'JACOBABAD JN.' },
  { value: '402', name: 'JAHANGIRA ROAD' },
  { value: '193', name: 'JAHANIA' },
  { value: '521', name: 'JALU-JO-CHUNRD' },
  { value: '589', name: 'JAMAN SHAH' },
  { value: '1023', name: 'JAMPUR' },
  { value: '474', name: 'JAMRANIWAH' },
  { value: '557', name: 'JAMRAO JN.' },
  { value: '774', name: 'JAND JN' },
  { value: '895', name: 'JARALA' },
  { value: '1084', name: 'JARANWALA' },
  { value: '703', name: 'JAURAH KARNANA' },
  { value: '788', name: 'JHALAR' },
  { value: '772', name: 'JHAMAT' },
  { value: '992', name: 'JHANG CITY' },
  { value: '991', name: 'JHANG SADADR' },
  { value: '361', name: 'JHELUM' },
  { value: '33', name: 'JHIMPIR' },
  { value: '1090', name: 'JHOK DITTA' },
  { value: '29', name: 'JUNGSHAHI' },
  { value: '476', name: 'KAHROR PAKKA' },
  { value: '1125', name: 'KALA KHATAI' },
  { value: '320', name: 'KALA SHAH KAKU' },
  { value: '617', name: 'KALLUR KOT' },
  { value: '1100', name: 'KAMALIA' },
  { value: '324', name: 'KAMOKE' },
  { value: '93', name: 'KANDHKOT' },
  { value: '507', name: 'KANGANPUR' },
  { value: '789', name: 'KANJUR' },
  { value: '1238', name: 'KANJWANI' },
  { value: '7', name: 'KARACHI CANTT' },
  { value: '1205', name: 'KARACHI CITY' },
  { value: '594', name: 'KAROR' },
  { value: '1059', name: 'KASHMOR COLONY' },
  { value: '515', name: 'KASUR JN.' },
  { value: '110', name: 'KHAIRPUR' },
  { value: '215', name: 'KHANEWAL JN' },
  { value: '154', name: 'KHANPUR JN.' },
  { value: '1246', name: 'KHATAKABAD' },
  { value: '463', name: 'KHATHAR' },
  { value: '45', name: 'KHOJAK' },
  { value: '519', name: 'KHOKHROPAR' },
  { value: '512', name: 'KHUDIAN' },
  { value: '42', name: 'KILA ABDULLA' },
  { value: '821', name: 'KILA SOBHA SINGH' },
  { value: '784', name: 'KOLPUR' },
  { value: '583', name: 'KOT ADU JN.' },
  { value: '1096', name: 'KOT KHAIR DIN (HALT)' },
  { value: '288', name: 'KOT LAKHPAT' },
  { value: '898', name: 'KOT NAJIB ULLAH' },
  { value: '281', name: 'KOT RADHA KISHEN' },
  { value: '587', name: 'KOT SULTAN' },
  { value: '89', name: 'KOT-LALLOO' },
  { value: '38', name: 'KOTRI JN.' },
  { value: '798', name: 'KUCHLAK' },
  { value: '206', name: 'KUHI-TAFTAN' },
  { value: '1211', name: 'KUNDIAN' },
  { value: '304', name: 'LAHORE CANTT' },
  { value: '305', name: 'LAHORE JN.' },
  { value: '100', name: 'LAKHA ROAD' },
  { value: '352', name: 'LALA MUSA JN.' },
  { value: '1058', name: 'LALIAN' },
  { value: '18', name: 'LANDHI JN.' },
  { value: '775', name: 'LANGAR' },
  { value: '57', name: 'LARKANA JN.' },
  { value: '590', name: 'LEIAH' },
  { value: '158', name: 'LIAQUATPUR' },
  { value: '185', name: 'LODHRAN JN.' },
  { value: '780', name: 'MACH' },
  { value: '486', name: 'MACHHIANWALA' },
  { value: '579', name: 'MAHMUD KOT' },
  { value: '102', name: 'MAHRABPUR' },
  { value: '480', name: 'MAILSI' },
  { value: '768', name: 'MAKHAD ROAD' },
  { value: '890', name: 'MAKHDUMPUR PAHORAN' },
  { value: '691', name: 'MALAKWAL JN.' },
  { value: '467', name: 'MALTI' },
  { value: '1098', name: 'MAMU KANJAN' },
  { value: '1222', name: 'MANDI AHMADABAD' },
  { value: '696', name: 'MANDI BAHA UD DIN' },
  { value: '488', name: 'MANDI BUREWALA' },
  { value: '1097', name: 'MANJHLA BAGH' },
  { value: '1070', name: 'MARGALA' },
  { value: '805', name: 'MARI INDUS' },
  { value: '1226', name: 'MARSHALLING YARD PIPRI' },
  { value: '739', name: 'MASSAN' },
  { value: '1129', name: 'MEHTA SUJA' },
  { value: '35', name: 'METING' },
  { value: '223', name: 'MIAN CHANNU' },
  { value: '734', name: 'MIAN WALI' },
  { value: '649', name: 'MIRPUR KHAS JN' },
  { value: '132', name: 'MIRPUR MATHELO' },
  { value: '1107', name: 'MISSAN KALAR' },
  { value: '1031', name: 'MITHAN KOT' },
  { value: '1220', name: 'MOMAN' },
  { value: '1047', name: 'MONA' },
  { value: '164', name: 'MUBARAKPUR' },
  { value: '990', name: 'MUDDUKI' },
  { value: '545', name: 'MULTAN CANTT' },
  { value: '322', name: 'MURIDKE' },
  { value: '573', name: 'MUZAFFARGARH' },
  { value: '777', name: 'NAMMAL' },
  { value: '1079', name: 'NANKANA SAHAB' },
  { value: '1127', name: 'NARANG' },
  { value: '824', name: 'NAROWAL JN.' },
  { value: '84', name: 'NAWABSHAH JN.' },
  { value: '523', name: 'NEW CHHOR' },
  { value: '1224', name: 'NEW MULTAN CITY' },
  { value: '1064', name: 'NISHTARABAD' },
  { value: '405', name: 'NOWSHERA JN.' },
  { value: '1253', name: 'NUR' },
  { value: '482', name: 'NUR SHAH' },
  { value: '55', name: 'ODEROLAL' },
  { value: '260', name: 'OKARA' },
  { value: '408', name: 'PABBI' },
  { value: '90', name: 'PADIDAN' },
  { value: '737', name: 'PAI KHEL' },
  { value: '1049', name: 'PAKHOWAL' },
  { value: '497', name: 'PAKPATTAN' },
  { value: '469', name: 'PALH' },
  { value: '1082', name: 'PANJ PULLA (HALT)' },
  { value: '127', name: 'PANO AKIL' },
  { value: '522', name: 'PARCHE-JI-VERI' },
  { value: '820', name: 'PASRUR' },
  { value: '277', name: 'PATTOKI' },
  { value: '1134', name: 'PEJOWALI' },
  { value: '412', name: 'PESHAWAR CANTT' },
  { value: '411', name: 'PESHAWAR CITY' },
  { value: '1045', name: 'PHULARWAN' },
  { value: '438', name: 'PIARO GOTH (HALT)' },
  { value: '1048', name: 'PIND MUKKO (HALT)' },
  { value: '619', name: 'PIPLAN' },
  { value: '1102', name: 'PIR MAHAL' },
  { value: '530', name: 'PITHORO JN' },
  { value: '1111', name: 'QILA SHEIKHUPURA' },
  { value: '793', name: 'QUETTA' },
  { value: '444', name: 'RADHAN' },
  { value: '151', name: 'RAHIM YAR KHAN' },
  { value: '283', name: 'RAIWIND JN.' },
  { value: '1029', name: 'RAJANPUR' },
  { value: '28', name: 'RAN PETHANI' },
  { value: '105', name: 'RANIPUR RIYASAT' },
  { value: '1243', name: 'RASHIDABAD' },
  { value: '1240', name: 'RATTO KALA' },
  { value: '384', name: 'RAWALPINDI' },
  { value: '1239', name: 'RAYA KHAS' },
  { value: '1244', name: 'REHMANI NAGAR' },
  { value: '550', name: 'RIAZABAD' },
  { value: '123', name: 'ROHRI JN.' },
  { value: '1088', name: 'RURALA ROAD' },
  { value: '988', name: 'RUSTAM SARGANA' },
  { value: '527', name: 'SADHAR (HALT)' },
  { value: '323', name: 'SADHOKE' },
  { value: '148', name: 'SADIKABAD ' },
  { value: '1219', name: 'SAFDARABAD' },
  { value: '946', name: 'SAHIANWALA' },
  { value: '255', name: 'SAHIWAL' },
  { value: '553', name: 'SAINDAD' },
  { value: '166', name: 'SAMASATA JN.' },
  { value: '981', name: 'SAMBRIAL' },
  { value: '581', name: 'SANAWAN' },
  { value: '1214', name: 'SANGLA HILL' },
  { value: '1065', name: 'SARGODHA JN.' },
  { value: '73', name: 'SARHARI' },
  { value: '1089', name: 'SARWAR SHAHEED (HALT)' },
  { value: '429', name: 'SEHWAN SHARIF' },
  { value: '901', name: 'SERAI SALEH' },
  { value: '104', name: 'SETHARJA' },
  { value: '554', name: 'SHADIPALLI' },
  { value: '997', name: 'SHAH JEWANA' },
  { value: '454', name: 'SHAH NAWAZ BHUTTO' },
  { value: '998', name: 'SHAH NIKDUR' },
  { value: '71', name: 'SHAHDADPUR' },
  { value: '307', name: 'SHAHDARA BAGH JN.' },
  { value: '1007', name: 'SHAHINABAD JN.' },
  { value: '795', name: 'SHEIKH MANDAH' },
  { value: '44', name: 'SHELABAGH' },
  { value: '542', name: 'SHER SHAH JN.' },
  { value: '712', name: 'SHIKARPUR' },
  { value: '1104', name: 'SHORKOT CANTT JN.' },
  { value: '538', name: 'SHUJABAD' },
  { value: '815', name: 'SIALKOT JN.' },
  { value: '753', name: 'SIBI JN.' },
  { value: '1004', name: 'SILLANWALI' },
  { value: '417', name: 'SIND UNIVERSITY' },
  { value: '979', name: 'SODHRA KOPRA' },
  { value: '767', name: 'SOHAN BRIDGE' },
  { value: '1000', name: 'SOHBAGA' },
  { value: '1123', name: 'SRIRAMPURA' },
  { value: '558', name: 'SUGAR MILL (HALT)' },
  { value: '965', name: 'SUKHEKE' },
  { value: '705', name: 'SUKKUR' },
  { value: '787', name: 'SULAIMANABAD' },
  { value: '470', name: 'TALHAR' },
  { value: '1092', name: 'TANDLIAWALA' },
  { value: '69', name: 'TANDO ADAM  ' },
  { value: '565', name: 'TANDO ALAHYAR' },
  { value: '568', name: 'TANDO JAM' },
  { value: '465', name: 'TANDO MUHAMMAD KHAN' },
  { value: '1245', name: 'TARNOUL  ' },
  { value: '1195', name: 'TAXILA CANTT' },
  { value: '926', name: 'TOBA TEK SINGH' },
  { value: '773', name: 'UCHHRI' },
  { value: '983', name: 'UGOKDE' },
  { value: '888', name: 'USMAN KHATTAR' },
  { value: '510', name: 'USMANWALA' },
  { value: '520', name: 'VASAR BAH' },
  { value: '484', name: 'VIHARI' },
  { value: '1252', name: 'WAGAH' },
  { value: '303', name: 'WALTON' },
  { value: '1077', name: 'WARBURTON' },
  { value: '987', name: 'WARYAM' },
  { value: '333', name: 'WAZIRABAD JN' },
  { value: '801', name: 'YARU' },
  { value: '536', name: 'ZARIF SHAHID' },
  { value: '460', name: 'ZEAL PAK' },
  { value: '1254', name: 'ZERO POINT' },
];
